"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Status = "Saved" | "Preparing" | "Applied" | "Interview" | "Offer";
type View = "today" | "applications" | "settings" | "details";
type Application = { id:number; title:string; organisation:string; location:string; deadline:string; status:Status; nextStep:string; updated:string; mark:string; markTone:string; source?:string; description?:string };
type ExtractedJob = { title:string; organisation:string; location:string; deadline:string; employmentType:string; requiredDocuments:string[]; source:string; evidence:Record<string,string> };

const stages: Status[] = ["Saved", "Preparing", "Applied", "Interview", "Offer"];
const seed: Application[] = [
  { id:1,title:"Research Assistant — Human Cognition",organisation:"University College London",location:"London · Hybrid",deadline:"2026-08-04",status:"Preparing",nextStep:"Finish cover letter",updated:"Today",mark:"UCL",markTone:"ink",source:"UCL Careers",description:"Support research investigating human cognition through study design, data collection and analysis." },
  { id:2,title:"DPhil Student — Neuroscience",organisation:"University of Oxford",location:"Oxford · On-site",deadline:"2026-08-19",status:"Applied",nextStep:"Follow up",updated:"Today",mark:"OX",markTone:"navy",source:"Oxford Jobs" },
  { id:3,title:"Senior UX Researcher",organisation:"Canva",location:"London · Hybrid",deadline:"2026-08-28",status:"Interview",nextStep:"Prepare for interview",updated:"Yesterday",mark:"CA",markTone:"violet",source:"Canva Careers" },
  { id:4,title:"Product Researcher",organisation:"Spotify",location:"London · Hybrid",deadline:"2026-09-03",status:"Saved",nextStep:"Review requirements",updated:"Yesterday",mark:"SP",markTone:"green",source:"Spotify Jobs" },
  { id:5,title:"Research Assistant",organisation:"London School of Economics",location:"London · On-site",deadline:"2026-08-02",status:"Preparing",nextStep:"Submit application",updated:"29 Jul",mark:"LSE",markTone:"red",source:"LSE Jobs" },
  { id:6,title:"Lab Assistant",organisation:"Wellcome Trust",location:"London · On-site",deadline:"2026-09-12",status:"Applied",nextStep:"Wait for response",updated:"28 Jul",mark:"W",markTone:"teal",source:"Wellcome Careers" },
  { id:7,title:"Research Coordinator",organisation:"University of Sydney",location:"Sydney · Hybrid",deadline:"2026-09-25",status:"Offer",nextStep:"Review offer",updated:"26 Jul",mark:"SYD",markTone:"charcoal",source:"Sydney Careers" },
];
const nextStepFor: Record<Status,string> = { Saved:"Review requirements",Preparing:"Finish application",Applied:"Wait for response",Interview:"Prepare for interview",Offer:"Review offer" };
const formatDate=(iso:string)=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${iso}T12:00:00`));
const daysUntil=(iso:string)=>{const now=new Date();now.setHours(0,0,0,0);return Math.ceil((new Date(`${iso}T00:00:00`).getTime()-now.getTime())/86400000)};

function Mark({app,large=false}:{app:Pick<Application,"mark"|"markTone"|"organisation">;large?:boolean}){return <span className={`org-mark ${app.markTone} ${large?"large":""}`}>{app.mark}</span>}
function Progress({status,onChange}:{status:Status;onChange?:(s:Status)=>void}){const active=stages.indexOf(status);return <div className="progress-control" aria-label={`Application progress: ${status}`}><div className="progress-line"><span style={{width:`${active/(stages.length-1)*100}%`}}/></div>{stages.map((stage,i)=><button type="button" key={stage} className={`progress-step ${i<active?"done":""} ${i===active?"current":""}`} onClick={()=>onChange?.(stage)} title={stage}><span/>{stage}</button>)}</div>}

export default function Home(){
  const [view,setView]=useState<View>("today"),[apps,setApps]=useState<Application[]>(seed),[selectedId,setSelectedId]=useState(1),[source,setSource]=useState(""),[importOpen,setImportOpen]=useState(false),[importStage,setImportStage]=useState(0),[extractError,setExtractError]=useState(""),[extracted,setExtracted]=useState<ExtractedJob|null>(null),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[savedToast,setSavedToast]=useState(false),[settings,setSettings]=useState({deadlines:true,followups:true,interviews:true});
  useEffect(()=>{try{const v=localStorage.getItem("haohire-applications");if(v)setApps(JSON.parse(v));const s=localStorage.getItem("haohire-settings");if(s)setSettings(JSON.parse(s))}catch{}},[]);
  useEffect(()=>localStorage.setItem("haohire-applications",JSON.stringify(apps)),[apps]);
  const selected=apps.find(a=>a.id===selectedId)??apps[0];
  const urgent=useMemo(()=>apps.filter(a=>daysUntil(a.deadline)<=7&&daysUntil(a.deadline)>=0).sort((a,b)=>a.deadline.localeCompare(b.deadline)),[apps]);
  const filtered=useMemo(()=>apps.filter(a=>{if(!`${a.title} ${a.organisation}`.toLowerCase().includes(query.toLowerCase()))return false;if(filter==="Needs action")return a.status==="Preparing"||a.status==="Interview";if(filter==="Deadline soon")return daysUntil(a.deadline)<=7;return true}),[apps,filter,query]);
  const go=(v:View)=>{setView(v);scrollTo({top:0,behavior:"smooth"})};
  const setStatus=(id:number,status:Status)=>setApps(list=>list.map(a=>a.id===id?{...a,status,nextStep:nextStepFor[status],updated:"Just now"}:a));
  const details=(id:number)=>{setSelectedId(id);go("details")};
  async function importJob(e?:FormEvent){e?.preventDefault();if(!source.trim())return;setImportOpen(true);setExtracted(null);setExtractError("");setImportStage(1);await new Promise(r=>setTimeout(r,400));setImportStage(2);try{const res=await fetch("/api/extract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source})});const data=await res.json();if(!res.ok)throw new Error(data.error??"We could not read this job.");setExtracted(data);setImportStage(3)}catch(err){setExtractError(err instanceof Error?err.message:"We could not read this job.");setImportStage(0)}}
  const addExtracted=()=>{if(!extracted)return;const org=extracted.organisation||"New organisation";const app:Application={id:Date.now(),title:extracted.title||"Untitled role",organisation:org,location:extracted.location||"Location not found",deadline:extracted.deadline||new Date(Date.now()+14*86400000).toISOString().slice(0,10),status:"Saved",nextStep:"Review requirements",updated:"Just now",mark:org.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(),markTone:"ink",source:extracted.source,description:"Imported from the original job posting."};setApps(x=>[app,...x]);setSelectedId(app.id);setImportOpen(false);setSource("");go("applications")};
  const saveSettings=()=>{localStorage.setItem("haohire-settings",JSON.stringify(settings));setSavedToast(true);setTimeout(()=>setSavedToast(false),2500)};
  const focusImport=()=>{go("today");setTimeout(()=>document.getElementById("job-source")?.focus(),30)};

  return <main className="app-frame">
    <aside className="sidebar"><button className="brand" onClick={()=>go("today")}><span className="brand-mark">H</span><span><strong>HaoHire</strong><small>How Hao gets hired.</small></span></button><nav><button className={view==="today"?"active":""} onClick={()=>go("today")}><span>☼</span>Today</button><button className={view==="applications"||view==="details"?"active":""} onClick={()=>go("applications")}><span>▣</span>Applications</button><button className={view==="settings"?"active":""} onClick={()=>go("settings")}><span>⚙</span>Settings</button></nav><button className="command-key" onClick={focusImport}>⌘ K</button></aside>
    <section className="workspace">
      {view==="today"&&<div className="today-layout page-enter"><section className="primary-column"><header className="page-header"><p className="eyebrow">Friday, 31 July</p><h1>Good morning, Hao</h1><p>Keep every application moving.</p></header><form className="capture" onSubmit={importJob}><span className="capture-icon">↗</span><textarea id="job-source" value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste a job URL or job description" rows={1}/><button className="primary-button" disabled={!source.trim()}>Import automatically <span>→</span></button></form><section className="attention-section"><div className="section-heading"><div><h2>Needs attention</h2><p>{urgent.length||2} applications with an upcoming action</p></div><button className="text-button" onClick={()=>go("applications")}>View all applications →</button></div><div className="attention-list">{(urgent.length?urgent.slice(0,3):apps.slice(0,3)).map(app=>{const d=daysUntil(app.deadline);return <article className="attention-row" key={app.id} onClick={()=>details(app.id)}><Mark app={app}/><div className="job-copy"><strong>{app.title}</strong><span>{app.organisation} · {app.location}</span></div><div className={`deadline-copy ${d<=7?"urgent":""}`}><span>{d>=0?`${d} days left`:"Deadline passed"}</span><small>{formatDate(app.deadline)}</small></div><button className="secondary-button" onClick={e=>{e.stopPropagation();details(app.id)}}>{app.nextStep}</button></article>})}</div></section></section><aside className="upcoming-rail"><div className="section-heading"><div><h2>Coming up</h2><p>Next deadlines</p></div></div><div className="timeline">{apps.slice().sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,6).map(app=><button key={app.id} onClick={()=>details(app.id)}><time><strong>{new Date(`${app.deadline}T12:00:00`).getDate()}</strong><span>{new Intl.DateTimeFormat("en-GB",{month:"short"}).format(new Date(`${app.deadline}T12:00:00`))}</span></time><Mark app={app}/><span><strong>{app.status==="Interview"?"Interview":daysUntil(app.deadline)<=7?"Deadline":app.nextStep}</strong><small>{app.title}</small></span></button>)}</div></aside></div>}
      {view==="applications"&&<div className="page-enter applications-page"><header className="page-header horizontal"><div><h1>Applications <span>{apps.length} applications</span></h1><p>One clear view of every opportunity.</p></div><button className="primary-button" onClick={focusImport}>Add a job</button></header><div className="table-toolbar"><label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search applications"/></label><div className="filter-tabs">{["All","Needs action","Deadline soon"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="application-table-wrap"><table className="application-table"><thead><tr><th>Job</th><th>Organisation</th><th>Deadline</th><th>Progress</th><th>Next step</th><th>Updated</th><th/></tr></thead><tbody>{filtered.map(app=>{const d=daysUntil(app.deadline);return <tr key={app.id}><td><button className="job-cell" onClick={()=>details(app.id)}><Mark app={app}/><strong>{app.title}</strong></button></td><td>{app.organisation}</td><td className={d<=7?"urgent":""}><strong>{formatDate(app.deadline)}</strong>{d<=7&&<small>{d} days left</small>}</td><td><Progress status={app.status} onChange={s=>setStatus(app.id,s)}/></td><td>{app.nextStep}</td><td>{app.updated}</td><td><button className="more-button" onClick={()=>details(app.id)}>•••</button></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty-state"><strong>No applications found</strong><span>Try another search or filter.</span></div>}<footer className="table-footer">1–{filtered.length} of {filtered.length}</footer></div></div>}
      {view==="details"&&selected&&<div className="page-enter details-page"><button className="back-button" onClick={()=>go("applications")}>← Applications</button><div className="details-grid"><section className="details-main"><header className="job-hero"><Mark app={selected} large/><div><h1>{selected.title}</h1><p>{selected.organisation}</p><span>{selected.location}</span></div><div className="hero-deadline"><span>Deadline</span><strong>{formatDate(selected.deadline)}</strong><small>{daysUntil(selected.deadline)} days left</small></div></header><section className="detail-section"><h2>Overview</h2><dl><div><dt>Organisation</dt><dd>{selected.organisation}</dd></div><div><dt>Location</dt><dd>{selected.location}</dd></div><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Imported</dt><dd>{selected.updated}</dd></div></dl></section><section className="detail-section"><h2>Job description</h2><p>{selected.description??"The original job description is saved with this application so it remains available after the posting closes."}</p></section><section className="detail-section"><h2>Required documents</h2><div className="checklist"><label><input type="checkbox" defaultChecked/>CV <span>Completed</span></label><label><input type="checkbox"/>Cover letter <span>In progress</span></label><label><input type="checkbox" defaultChecked/>Two references <span>Completed</span></label></div></section><section className="detail-section"><h2>Notes</h2><textarea defaultValue="Focus on relevant research methods and data analysis experience."/></section></section><aside className="progress-panel"><h2>Application progress</h2><Progress status={selected.status} onChange={s=>setStatus(selected.id,s)}/><label>Next step<select value={selected.nextStep} onChange={e=>setApps(x=>x.map(a=>a.id===selected.id?{...a,nextStep:e.target.value}:a))}>{[...Object.values(nextStepFor),"Follow up","Submit application"].map(x=><option key={x}>{x}</option>)}</select></label><label>Deadline<input type="date" value={selected.deadline} onChange={e=>setApps(x=>x.map(a=>a.id===selected.id?{...a,deadline:e.target.value}:a))}/></label><button className="primary-button full" onClick={()=>setStatus(selected.id,"Applied")}>Mark as applied</button><div className="reminder-note"><span>♢</span><div><strong>Deadline reminder</strong><small>3 days before the deadline</small></div></div></aside></div></div>}
      {view==="settings"&&<div className="page-enter settings-page"><header className="page-header"><h1>Settings</h1><p>Choose how HaoHire reminds you.</p></header><section className="settings-group"><h2>Reminders</h2><SettingRow title="Deadline reminders" description="Get reminded before application deadlines." checked={settings.deadlines} onChange={v=>setSettings({...settings,deadlines:v})}><select><option>7 · 3 · 1 days before</option><option>3 · 1 days before</option></select></SettingRow><SettingRow title="Follow-up reminders" description="Get reminded after applying." checked={settings.followups} onChange={v=>setSettings({...settings,followups:v})}><select><option>10 days after applying</option><option>7 days after applying</option></select></SettingRow><SettingRow title="Interview reminders" description="Get reminded about upcoming interviews." checked={settings.interviews} onChange={v=>setSettings({...settings,interviews:v})}/></section><section className="settings-group"><h2>Application defaults</h2><div className="plain-setting"><span><strong>Default status</strong><small>Set when you add a new application.</small></span><select><option>Saved</option><option>Preparing</option></select></div><div className="plain-setting"><span><strong>Timezone</strong><small>Used for reminders and dates.</small></span><select><option>Europe/London</option></select></div></section><section className="settings-group"><h2>Account</h2><div className="plain-setting"><span><strong>Name</strong></span><span>Hao Chen</span></div><div className="plain-setting"><span><strong>Email</strong></span><span>hao@example.com</span></div></section><div className="settings-bar"><span>Preferences are saved on this device.</span><button className="primary-button" onClick={saveSettings}>Save changes</button></div>{savedToast&&<div className="toast">✓ Changes saved</div>}</div>}
    </section>
    {importOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setImportOpen(false)}}><section className="import-modal" role="dialog" aria-modal="true"><button className="close-button" onClick={()=>setImportOpen(false)}>×</button><header><p className="eyebrow">Smart import</p><h2>Add a job</h2><p>HaoHire reads the source and fills in the details.</p></header><div className="import-progress">{["Reading source","Extracting details","Ready to add"].map((label,i)=><div className={importStage>i?"complete":importStage===i+1?"active":""} key={label}><span>{importStage>i?"✓":i+1}</span>{label}</div>)}</div>{extractError&&<div className="error-message"><strong>Import failed</strong><span>{extractError}</span><button onClick={()=>importJob()}>Try again</button></div>}{!extracted&&!extractError&&<div className="extract-skeleton"><span/><span/><span/><span/></div>}{extracted&&<div className="extracted-job"><div className="extracted-title"><span className="org-mark ink large">{extracted.organisation.split(/\s+/).slice(0,2).map(w=>w[0]).join("")}</span><div><h3>{extracted.title}</h3><p>{extracted.organisation}</p></div></div><dl>{[["Location",extracted.location,extracted.evidence.location],["Deadline",extracted.deadline?formatDate(extracted.deadline):"Not found",extracted.evidence.deadline],["Employment type",extracted.employmentType,extracted.evidence.employmentType],["Required",extracted.requiredDocuments.join(", ")||"Needs review",extracted.evidence.requiredDocuments]].map(([l,v,e])=><div key={l}><dt>{l}</dt><dd>{v}</dd><span className={v==="Needs review"||v==="Not found"?"review":"verified"}>{e||"Needs review"}</span></div>)}</dl><footer><button className="secondary-button" onClick={()=>setImportOpen(false)}>Edit source</button><button className="primary-button" onClick={addExtracted}>Add to applications →</button></footer></div>}</section></div>}
  </main>
}

function SettingRow({title,description,checked,onChange,children}:{title:string;description:string;checked:boolean;onChange:(v:boolean)=>void;children?:React.ReactNode}){return <div className="setting-row"><span><strong>{title}</strong><small>{description}</small></span>{children}<label className="switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span/></label></div>}
