import { NextRequest, NextResponse } from "next/server";

type JobResult={title:string;organisation:string;location:string;deadline:string;employmentType:string;source:string;evidence:Record<string,string>};
const textValue=(v:unknown):string=>{if(typeof v==="string")return v;if(Array.isArray(v))return v.map(textValue).filter(Boolean).join(", ");if(v&&typeof v==="object"){const r=v as Record<string,unknown>;return textValue(r.name??r.addressLocality??r.addressCountry??"")}return ""};
const normalizeDate=(v:string)=>{if(!v)return "";const exact=v.match(/\b(\d{4}-\d{2}-\d{2})\b/);if(exact)return exact[1];const d=new Date(v);if(Number.isNaN(d.getTime()))return "";return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const stripHtml=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const pick=(text:string,patterns:RegExp[])=>{for(const p of patterns){const m=text.match(p);if(m?.[1])return m[1].trim().replace(/[|•].*$/,"").trim()}return ""};
function fromText(text:string,source:string):JobResult{const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const title=pick(text,[/job\s*title\s*[:\-]\s*([^\n]+)/i,/position\s*[:\-]\s*([^\n]+)/i])||lines[0]?.slice(0,100)||"Job opportunity";const organisation=pick(text,[/(?:company|organisation|organization|university|institution)\s*[:\-]\s*([^\n]+)/i])||(text.match(/University (?:College )?London|University of Oxford|London School of Economics/i)?.[0]??"Organisation not found");const location=pick(text,[/location\s*[:\-]\s*([^\n]+)/i])||"Location not found";const deadline=normalizeDate(pick(text,[/(?:closing date|deadline|apply by)\s*[:\-]\s*([^\n.]+)/i]));return{title,organisation,location,deadline,employmentType:pick(text,[/employment type\s*[:\-]\s*([^\n]+)/i,/\b(full[- ]time|part[- ]time|fixed[- ]term|internship)\b/i])||"Not specified",source,evidence:{location:location==="Location not found"?"Needs review":"Job description",deadline:deadline?"Job description":"Needs review",employmentType:"Job description"}}}
function privateHost(hostname:string){const h=hostname.toLowerCase();return h==="localhost"||h==="0.0.0.0"||h==="::1"||h.endsWith(".local")||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||/^169\.254\./.test(h)}
export async function POST(request:NextRequest){try{const body=await request.json() as{source?:string};const source=body.source?.trim();if(!source||source.length>120000)return NextResponse.json({error:"Paste a job URL or job description."},{status:400});if(!/^https?:\/\//i.test(source))return NextResponse.json(fromText(source,"Pasted job description"));const url=new URL(source);if(url.protocol!=="https:"||privateHost(url.hostname))return NextResponse.json({error:"Only public HTTPS job pages can be imported."},{status:400});const response=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(8000),headers:{"User-Agent":"HaoHire Job Importer/1.0"}});if(!response.ok)throw new Error("This page could not be opened. Paste the job description instead.");if(Number(response.headers.get("content-length")??0)>2_000_000)throw new Error("This page is too large. Paste the job description instead.");const html=(await response.text()).slice(0,2_000_000);const blocks=[...html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];for(const block of blocks){try{const parsed=JSON.parse(block[1]);const candidates=Array.isArray(parsed)?parsed:parsed["@graph"]??[parsed];const posting=candidates.find((item:Record<string,unknown>)=>item?.["@type"]==="JobPosting");if(posting){const location=textValue(posting.jobLocation)||textValue(posting.applicantLocationRequirements)||"Location not found";return NextResponse.json({title:textValue(posting.title)||"Job opportunity",organisation:textValue(posting.hiringOrganization)||url.hostname.replace(/^www\./,""),location,deadline:normalizeDate(textValue(posting.validThrough)),employmentType:textValue(posting.employmentType)||"Not specified",source:url.toString(),evidence:{location:"Page metadata",deadline:"Page metadata",employmentType:"Page metadata"}} satisfies JobResult)}}catch{}}const text=stripHtml(html);const metaTitle=html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]||html.match(/<title[^>]*>([^<]+)/i)?.[1]||"";const result=fromText(`${metaTitle}\n${text}`,url.toString());if(result.organisation==="Organisation not found")result.organisation=url.hostname.replace(/^www\./,"").split(".")[0].replace(/\b\w/g,l=>l.toUpperCase());return NextResponse.json(result)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"This job could not be imported."},{status:422})}}
